name: RsBlocks
version: 1.2-BETA
main: com.dozz3s.rsblocks.RsBlocks
api-version: 1.16
commands:
  rsblocks:
    description: Команды RsBlocks
    usage: /rsblocks give <игрок> <тип> или /rsblocks reload
    permission: rsblocks.adm
permissions:
  rsblocks.adm:
    description: Разрешает комманды плагина
    default: op